import json
from pathlib import Path
from unittest.mock import patch


def test_worktree_create_endpoint_writes_hooks(tmp_path, monkeypatch, client, db_session):
    """When POST /tasks/{id}/worktree succeeds, hooks are written to the worktree dir."""
    monkeypatch.setenv("HOME", str(tmp_path))

    from app.models.project import Project
    from app.models.task import Task
    from app.models.worktree_config import WorktreeConfig

    proj = Project(name="P")
    db_session.add(proj)
    db_session.commit()
    db_session.refresh(proj)

    task = Task(project_id=proj.id, title="T")
    db_session.add(task)
    db_session.commit()
    db_session.refresh(task)

    cfg = WorktreeConfig(
        name="c",
        branch_template="b-{task_id_short}",
        dir_template=str(tmp_path / "wt-{task_id_short}"),
        base_repo_path=str(tmp_path / "repo"),
    )
    db_session.add(cfg)
    db_session.commit()
    db_session.refresh(cfg)

    # Stub out git operations (router imports these names into its own namespace,
    # so patch the router module's bindings).
    with patch("app.routers.worktrees.validate_repo", return_value={"valid": True, "error": None}), \
         patch("app.routers.worktrees.create_worktree", return_value={"success": True, "error": None}):
        resp = client.post(f"/api/v1/tasks/{task.id}/worktree", json={"config_id": cfg.id})
    assert resp.status_code == 201

    wt_path = resp.json()["path"]
    settings = Path(wt_path) / ".claude" / "settings.json"
    assert settings.exists()
    data = json.loads(settings.read_text())
    assert "Stop" in data["hooks"]

    # opencode plugin installed alongside the Claude Code hooks.
    plugin = Path(wt_path) / ".opencode" / "plugins" / "kanban-forwarder.js"
    assert plugin.exists()
    assert "Generated by kanban" in plugin.read_text()


def test_worktree_delete_endpoint_removes_hooks(tmp_path, monkeypatch, client, db_session):
    monkeypatch.setenv("HOME", str(tmp_path))

    from app.models.project import Project
    from app.models.task import Task
    from app.models.worktree import Worktree
    from app.models.worktree_config import WorktreeConfig

    proj = Project(name="P")
    db_session.add(proj)
    db_session.commit()
    db_session.refresh(proj)

    task = Task(project_id=proj.id, title="T")
    db_session.add(task)
    db_session.commit()
    db_session.refresh(task)

    wt_path = tmp_path / "wt-xyz"
    (wt_path / ".claude").mkdir(parents=True)
    settings = wt_path / ".claude" / "settings.json"
    settings.write_text(json.dumps({
        "hooks": {
            "Stop": [
                {"hooks": [{"type": "command", "command": "/x/.config/kanban/hooks/claude-code-forwarder.sh"}]}
            ]
        }
    }))
    # Simulate the opencode plugin that worktree creation would have written.
    plugin_dir = wt_path / ".opencode" / "plugins"
    plugin_dir.mkdir(parents=True)
    plugin = plugin_dir / "kanban-forwarder.js"
    plugin.write_text("// Generated by kanban. opencode forwarder\n")

    cfg = WorktreeConfig(
        name="c",
        branch_template="b",
        dir_template=str(wt_path),
        base_repo_path=str(tmp_path / "repo"),
    )
    db_session.add(cfg)
    db_session.commit()
    db_session.refresh(cfg)

    wt = Worktree(
        task_id=task.id,
        config_id=cfg.id,
        branch="b",
        path=str(wt_path),
        status="active",
    )
    db_session.add(wt)
    db_session.commit()
    db_session.refresh(wt)

    task.worktree_id = wt.id
    db_session.commit()

    with patch("app.routers.worktrees.remove_worktree", return_value={"success": True, "error": None}):
        resp = client.delete(f"/api/v1/tasks/{task.id}/worktree")
    assert resp.status_code == 204
    # File should be deleted because the only entries were ours.
    assert not settings.exists()
    # opencode plugin cleaned up too.
    assert not plugin.exists()


def test_worktree_delete_cleans_hooks_even_when_git_remove_fails(tmp_path, monkeypatch, client, db_session):
    """Hook cleanup must run BEFORE `git worktree remove` so that if git fails,
    the kanban-managed hooks are still removed and the user can retry safely.
    """
    monkeypatch.setenv("HOME", str(tmp_path))

    from app.models.project import Project
    from app.models.task import Task
    from app.models.worktree import Worktree
    from app.models.worktree_config import WorktreeConfig

    proj = Project(name="P")
    db_session.add(proj)
    db_session.commit()
    db_session.refresh(proj)

    task = Task(project_id=proj.id, title="T")
    db_session.add(task)
    db_session.commit()
    db_session.refresh(task)

    wt_path = tmp_path / "wt-fail"
    (wt_path / ".claude").mkdir(parents=True)
    settings = wt_path / ".claude" / "settings.json"
    settings.write_text(json.dumps({
        "hooks": {
            "Stop": [
                {"hooks": [{"type": "command", "command": "/x/.config/kanban/hooks/claude-code-forwarder.sh"}]}
            ]
        }
    }))

    cfg = WorktreeConfig(
        name="c",
        branch_template="b",
        dir_template=str(wt_path),
        base_repo_path=str(tmp_path / "repo"),
    )
    db_session.add(cfg)
    db_session.commit()
    db_session.refresh(cfg)

    wt = Worktree(
        task_id=task.id,
        config_id=cfg.id,
        branch="b",
        path=str(wt_path),
        status="active",
    )
    db_session.add(wt)
    db_session.commit()
    db_session.refresh(wt)

    task.worktree_id = wt.id
    db_session.commit()

    # `git worktree remove` failing should NOT block DB cleanup: the record
    # is still marked removed (204) so the user isn't stuck. Hooks must
    # already be cleaned up regardless.
    with patch("app.routers.worktrees.remove_worktree",
               return_value={"success": False, "error": "git failed"}):
        resp = client.delete(f"/api/v1/tasks/{task.id}/worktree")
    assert resp.status_code == 204

    # The kanban-managed hook entries should be gone even though git failed,
    # proving that hook cleanup ran BEFORE the git call.
    assert not settings.exists()
