"""opencode hook writer — worktree-scoped plugin injection.

Mirrors `worktree_hooks.py` (Claude Code) but for opencode. Instead of a
global forwarder script + settings.json entries, opencode auto-loads any
JS/TS file dropped in `.opencode/plugins/`, so we simply write a self-
contained forwarder plugin into each worktree. The plugin listens to
session events and POSTs to the same `/agent-events` endpoint that the
Claude Code forwarder uses, so one set of notification channels covers
both tools.

opencode events are mapped to Claude Code-equivalent event_type values so
that channel `event_filters` (e.g. ["Stop"]) match regardless of which
agent produced the event.
"""
import os
from pathlib import Path


OPENCODE_PLUGIN_DIR = ".opencode/plugins"
OPENCODE_PLUGIN_FILENAME = "kanban-forwarder.js"
PLUGIN_MARKER = "Generated by kanban"

# opencode events we forward, mapped to the Claude Code-equivalent
# event_type. Keeping the names aligned means a channel filtered on
# "Stop" fires for both Claude Code's Stop hook AND opencode's
# session.idle.
EVENT_MAP = {
    "session.idle": ("Stop", "opencode turn complete (session idle)"),
    "session.error": ("Notification", "opencode session error"),
    "permission.asked": ("Notification", "opencode requests permission"),
}

PLUGIN_BODY = """\
// Generated by kanban. Forwards opencode session events to kanban's
// notification pipeline. To reconfigure, edit kanban Settings UI —
// do not edit this file.
const KANBAN_URL = "http://{kanban_host}/api/v1/agent-events"

// opencode event.type -> { event_type, message }
const EVENT_MAP = {
  {entries}
}

export const KanbanForwarderPlugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      const mapped = EVENT_MAP[event.type]
      if (!mapped) return
      const body = {
        event_type: mapped.event_type,
        agent: "opencode",
        cwd: directory,
        message: mapped.message,
        context: { opencode_event: event.type },
      }
      try {
        await fetch(KANBAN_URL, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
        })
      } catch (e) {
        // never let the plugin break the agent
      }
    },
  }
}
"""


def _plugin_path(worktree_path: str | Path) -> Path:
    return Path(worktree_path) / OPENCODE_PLUGIN_DIR / OPENCODE_PLUGIN_FILENAME


def _render_body(kanban_host: str = "localhost:9527") -> str:
    entries = ",\n  ".join(
        f'"{ev}": {{ event_type: "{et}", message: "{msg}" }}'
        for ev, (et, msg) in EVENT_MAP.items()
    )
    return (
        PLUGIN_BODY
        .replace("{kanban_host}", kanban_host)
        .replace("{entries}", entries)
    )


def _atomic_write_text(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def write_plugin_to_worktree(
    worktree_path: str | Path,
    kanban_host: str = "localhost:9527",
) -> dict:
    """Ensure the kanban forwarder plugin exists in the worktree.

    Idempotent: if our plugin is already present and up to date this is a
    no-op. If a same-named file exists that we did not generate, it is
    left untouched. Atomic: writes to a tmp file then renames.
    """
    target = _plugin_path(worktree_path)
    body = _render_body(kanban_host)

    if target.exists():
        existing = target.read_text()
        if existing == body:
            return {"installed": False, "updated": False, "path": str(target)}
        if PLUGIN_MARKER in existing:
            _atomic_write_text(target, body)
            return {"installed": False, "updated": True, "path": str(target)}
        # A user-owned file with the same name — do not clobber it.
        return {"installed": False, "updated": False, "path": str(target), "skipped": "foreign_file"}

    target.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write_text(target, body)
    return {"installed": True, "updated": False, "path": str(target)}


def remove_plugin_from_worktree(worktree_path: str | Path) -> dict:
    """Remove the kanban forwarder plugin if we own it. Leaves other files alone."""
    target = _plugin_path(worktree_path)
    if not target.exists():
        return {"removed": False, "existed": False}

    existing = target.read_text()
    if PLUGIN_MARKER not in existing:
        return {"removed": False, "existed": True, "skipped": "foreign_file"}

    target.unlink()
    # Clean up now-empty plugin dir / .opencode dir if we created them and
    # nothing else landed there. Never remove a non-empty directory.
    plugins_dir = target.parent
    opencode_dir = plugins_dir.parent
    try:
        if plugins_dir != opencode_dir and not any(plugins_dir.iterdir()):
            plugins_dir.rmdir()
        if not any(opencode_dir.iterdir()):
            opencode_dir.rmdir()
    except OSError:
        pass  # not empty or no permission — leave as-is
    return {"removed": True, "existed": True}
