import json
import os
import stat
from pathlib import Path


HOOK_EVENTS = ("Stop", "Notification", "SubagentStop", "SessionEnd")
FORWARDER_PATH = "~/.config/kanban/hooks/claude-code-forwarder.sh"
FORWARDER_MARKER = "claude-code-forwarder.sh"

FORWARDER_SCRIPT_BODY = """#!/usr/bin/env bash
# Generated by kanban. Forwards Claude Code hook stdin to kanban.
# To reconfigure, edit kanban Settings UI — do not edit this file.
input=$(cat)
curl -s -X POST http://{kanban_host}/api/v1/agent-events \\
  -H 'Content-Type: application/json' \\
  --data-binary "$input" \\
  >/dev/null 2>&1 & disown
exit 0
"""


def _forwarder_path() -> Path:
    return Path(FORWARDER_PATH).expanduser()


def ensure_forwarder_script(kanban_host: str = "localhost:9527", force: bool = False) -> Path:
    """Write the forwarder script. Idempotent by default; pass force=True to overwrite."""
    target = _forwarder_path()
    if target.exists() and not force:
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    body = FORWARDER_SCRIPT_BODY.replace("{kanban_host}", kanban_host)
    target.write_text(body)
    # chmod +x for user/owner
    mode = target.stat().st_mode
    target.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


def _is_our_entry(entry: dict) -> bool:
    """True if this hook entry points at our forwarder script."""
    try:
        for h in entry.get("hooks", []):
            cmd = h.get("command", "")
            if FORWARDER_MARKER in cmd:
                return True
    except Exception:
        pass
    return False


def _our_entry() -> dict:
    return {
        "hooks": [
            {
                "type": "command",
                "command": FORWARDER_PATH,
            }
        ]
    }


def write_hooks_to_worktree(worktree_path: str | Path) -> dict:
    """Merge our hook entries into <worktree_path>/.claude/settings.json.

    Idempotent: re-running does not duplicate entries.
    Atomic: writes to a tmp file then renames.
    Preserves all user-owned entries.
    """
    settings_path = Path(worktree_path) / ".claude" / "settings.json"
    settings_path.parent.mkdir(parents=True, exist_ok=True)

    if settings_path.exists():
        try:
            data = json.loads(settings_path.read_text() or "{}")
            if not isinstance(data, dict):
                data = {}
        except json.JSONDecodeError:
            data = {}
    else:
        data = {}

    hooks = data.setdefault("hooks", {})
    installed = []
    unchanged = []
    for event in HOOK_EVENTS:
        entries = hooks.setdefault(event, [])
        existing_idx = next((i for i, e in enumerate(entries) if _is_our_entry(e)), None)
        our = _our_entry()
        if existing_idx is not None:
            entries[existing_idx] = our
            unchanged.append(event)
        else:
            entries.append(our)
            installed.append(event)

    _atomic_write_json(settings_path, data)
    return {"installed": installed, "unchanged": unchanged}


def remove_hooks_from_worktree(worktree_path: str | Path) -> dict:
    """Drop all hook entries pointing at our forwarder. Preserve everything else."""
    settings_path = Path(worktree_path) / ".claude" / "settings.json"
    if not settings_path.exists():
        return {"removed_events": [], "deleted_file": False}

    try:
        data = json.loads(settings_path.read_text() or "{}")
        if not isinstance(data, dict):
            return {"removed_events": [], "deleted_file": False}
    except json.JSONDecodeError:
        return {"removed_events": [], "deleted_file": False}

    hooks = data.get("hooks", {})
    removed = []
    for event in HOOK_EVENTS:
        if event not in hooks:
            continue
        before = len(hooks[event])
        hooks[event] = [e for e in hooks[event] if not _is_our_entry(e)]
        removed_count = before - len(hooks[event])
        if removed_count > 0:
            removed.append(event)
        if not hooks[event]:
            del hooks[event]

    # If hooks object is now empty, drop the key entirely.
    if not hooks:
        data.pop("hooks", None)

    # If file is now empty, delete it. Otherwise atomic-write.
    if not data:
        settings_path.unlink()
        return {"removed_events": removed, "deleted_file": True}

    _atomic_write_json(settings_path, data)
    return {"removed_events": removed, "deleted_file": False}


def _atomic_write_json(path: Path, data: dict) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    os.replace(tmp, path)
